[package]
name = "binary_search"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
size = "0.5.0"

[profile.release]
debug = true
